[package]
name = "canopus-api"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
rocket = { workspace = true, features = ["json"] }
uuid = { workspace = true }

canopus-engine = { workspace = true }
