[package]
name = "Canopus"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio", "uuid"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
uuid = { version = "1.13.1", features = ["v4"] }
