[workspace]
resolver = "3"
members = [
    "crates/canopus-dataspine",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
dotenvy = "0.15.7"
sqlx = "0.8.3"
tokio = "1.43.0"
uuid = "1.13.1"

canopus-dataspine = { path = "crates/canopus-dataspine"}
