[package]
name = "canopus-wire"
version = "0.1.0"
edition = { workspace = true }

[lib]
name = "canopus_wire"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }

canopus-definitions = { workspace = true }
