[package]
name = "canopus-protocol"
version = "0.1.0"
edition = { workspace = true }

[lib]
name = "canopus_protocol"

[dependencies]
chrono = { workspace = true }
csv = { workspace = true }
eyre = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
