[package]
name = "canopus-cli"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true }

canopus-engine = { workspace = true }
