[package]
name = "canopus-cli"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true }

canopus-engine = { workspace = true }
canopus-protocol = { workspace = true }
